var User = require('../api/user/user.model');

User.find({}).remove(function() {
  User.create({
    provider: 'local',
    name: 'Test User',
    email: 'test@test.com',
    password: 'test'
  }, {
    provider: 'local',
    role: 'admin',
    name: 'Admin',
    email: 'admin@admin.com',
    password: 'admin'
  }, {
    provider: 'local',
    name: 'vas',
    email: 'vasilievvk@yandex.ru',
    password: 'vaspass',
    personal: {
      firstname: 'Валерий',
      patronymic: 'Константинович',
      lastname: 'Васильев',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '+7(903)2101941',
      birthdate: new Date('1986-11-19'),
    },
  }, {
    provider: 'local',
    name: 'vor',
    email: 'voregor162@yandex.ru',
    password: 'vorpass',
    personal: {
      firstname: 'Егор',
      patronymic: 'Станиславович',
      lastname: 'Воронцов',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '89031239037',
      birthdate: new Date('1991-04-30'),
    },
  }, {
    provider: 'local',
    name: 'gol',
    email: 'avgolovin@bk.ru',
    password: 'vorpass',
    personal: {
      firstname: 'Анатолий',
      patronymic: 'Владимирович',
      lastname: 'Головин',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '8-903-766-85-56',
      birthdate: new Date('1983-01-18'),
    },
  }, {
    provider: 'local',
    name: 'gro',
    email: 'gro@site.com',
    password: 'gropass',
    personal: {
      firstname: 'Евгений',
      patronymic: '',
      lastname: 'Громов',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '+7 (905) 725-04-47',
    },
  }, {
    provider: 'local',
    name: 'desh',
    email: 'TheMarquis@mail.ru',
    password: 'deshpass',
    personal: {
      firstname: 'Сергей',
      patronymic: 'Игоревич',
      lastname: 'Дёшин',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '89039670837',
      birthdate: new Date('1990-02-02'),
    },
  }, {
    provider: 'local',
    name: 'zai',
    email: 'mephista1-11@yandex.ru',
    password: 'zaipass',
    personal: {
      firstname: 'Сергей',
      patronymic: 'Александрович',
      lastname: 'Заикин',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '+7 (916) 135-24-33',
      birthdate: new Date('1990-05-11'),
    },
  }, {
    provider: 'local',
    name: 'iva',
    email: 'ivanovnew@yandex.ru',
    password: 'ivapass',
    personal: {
      firstname: 'Игорь',
      patronymic: 'Александрович',
      lastname: 'Иванов',
      photo: 'http://www.estatesale.com/img/no_image.gif',
    },
  }, {
    provider: 'local',
    name: 'kas',
    email: 'kaskov.s@gmail.com',
    password: 'kaspass',
    personal: {
      firstname: 'Сергей',
      patronymic: 'Юрьевич',
      lastname: 'Касков',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '+7 916 373-69-34',
      birthdate: new Date('1986-05-09'),
    },
  }, {
    provider: 'local',
    name: 'mak',
    email: 'malvina12@inbox.ru',
    password: 'makpass',
    personal: {
      firstname: 'Нина',
      patronymic: 'Валерьевна',
      lastname: 'Макарова',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '+7 (926) 626-97-35',
      birthdate: new Date('1991-03-12'),
    },
  }, {
    provider: 'local',
    name: 'mal',
    email: 'malkin_evgeniy@mail.ru',
    password: 'malpass',
    personal: {
      firstname: 'Евгений',
      patronymic: 'Константинович',
      lastname: 'Малкин',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '+7 (926) 594-04-51',
      birthdate: new Date('1986-05-20'),
    },
  }, {
    provider: 'local',
    name: 'mat',
    email: 'maksim-starcity@mail.ru',
    password: 'matpass',
    personal: {
      firstname: 'Максим',
      patronymic: 'Александрович',
      lastname: 'Матуско',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '9162488779',
      birthdate: new Date('1991-05-09'),
    },
  }, {
    provider: 'local',
    name: 'mim',
    email: 'MiRus398@yandex.ru',
    password: 'mimpass',
    personal: {
      firstname: 'Руслан',
      patronymic: 'Режепгулыевич',
      lastname: 'Миминов',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '89163880074',
      birthdate: new Date('1990-07-20'),
    },
  }, {
    provider: 'local',
    name: 'mir',
    email: 'Chrno91@mail.ru',
    password: 'mirpass',
    personal: {
      firstname: 'Александр',
      patronymic: 'Сергеевич',
      lastname: 'Миронов',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '+7 915 371-72-98',
      birthdate: new Date('1991-04-04'),
    },
  }, {
    provider: 'local',
    name: 'pot',
    email: 'Potur92@mail.ru',
    password: 'potpass',
    personal: {
      firstname: 'Артемий',
      patronymic: 'Андреевич',
      lastname: 'Потуруй',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '89104679397',
      birthdate: new Date('1992-03-28'),
    },
  }, {
    provider: 'local',
    name: 'riz',
    email: 'tlb18@mail.ru',
    password: 'rizpass',
    personal: {
      firstname: 'Дмитрий',
      patronymic: 'Николаевич',
      lastname: 'Рыжов',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '8-916-344-34-24',
      birthdate: new Date('1990-04-20'),
    },
  }, {
    provider: 'local',
    name: 'zar',
    email: 'neyania@yandex.ru',
    password: 'zarpass',
    personal: {
      firstname: 'Наталия',
      patronymic: 'Олеговна',
      lastname: 'Сарычева',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '89091674712',
      birthdate: new Date('1991-05-07'),
    },
  }, {
    provider: 'local',
    name: 'stel',
    email: 'evzhenya92@gmail.com',
    password: 'stelpass',
    personal: {
      firstname: 'Женя',
      patronymic: 'Федоровна',
      lastname: 'Стельмашенко',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '89257111714',
      birthdate: new Date('1992-04-26'),
    },
  }, {
    provider: 'local',
    name: 'tay',
    email: 'lev.tajdakov@gmail.com',
    password: 'taypass',
    personal: {
      firstname: 'Лев',
      patronymic: 'Олегович',
      lastname: 'Тайдаков',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '+79263853207',
      birthdate: new Date('1990-08-02'),
    },
  }, {
    provider: 'local',
    name: 'zig',
    email: '__stdc__@ascii.org.ru',
    password: 'zigpass',
    personal: {
      firstname: 'Александр',
      patronymic: 'Игоревич',
      lastname: 'Цыганкин',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '+7-926-629-6915',
      birthdate: new Date('1989-11-13'),
    },
  }, {
    provider: 'local',
    name: 'shal',
    email: 'shaltaeva@yandex.ru',
    password: 'shalpass',
    personal: {
      firstname: 'Юлия',
      patronymic: 'Ринатовна',
      lastname: 'Шалтаева',
      photo: 'http://www.estatesale.com/img/no_image.gif',
      phone: '89167268775',
      birthdate: new Date('1990-04-18'),
    },
  }, function() {
      console.log('finished populating users');
    }
  );
});
